import io
import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4

def _styles():
    return {
        'title': ParagraphStyle('title',
            fontName='Times-Bold', fontSize=28, leading=32,
            textColor=colors.HexColor('#0F172A'), spaceAfter=6), # Rich Dark Navy Blue
        'sub': ParagraphStyle('sub',
            fontName='Times-Roman', fontSize=10, leading=14,
            textColor=colors.HexColor('#475569'), spaceAfter=14),
        'h2': ParagraphStyle('h2',
            fontName='Times-Bold', fontSize=15, leading=19,
            textColor=colors.HexColor('#1E3A8A'), spaceBefore=16, spaceAfter=8), # Dark Navy Blue for subheadings
        'body': ParagraphStyle('body',
            fontName='Times-Roman', fontSize=10, leading=15,
            textColor=colors.HexColor('#475569'), spaceAfter=8),
        'th': ParagraphStyle('th',
            fontName='Times-Bold', fontSize=9.5, leading=12,
            textColor=colors.HexColor('#1E293B'), alignment=0), 
        'th_center': ParagraphStyle('th_center',
            fontName='Times-Bold', fontSize=9.5, leading=12,
            textColor=colors.HexColor('#1E293B'), alignment=1), 
        'td': ParagraphStyle('td',
            fontName='Times-Roman', fontSize=9.5, leading=13,
            textColor=colors.HexColor('#334155')),
        'td_center': ParagraphStyle('td_center',
            fontName='Times-Roman', fontSize=9.5, leading=13,
            textColor=colors.HexColor('#334155'), alignment=1),
        'verdict_safe': ParagraphStyle('v_safe',
            fontName='Times-Bold', fontSize=9.5, leading=12,
            textColor=colors.HexColor('#16A34A'), alignment=1),
        'verdict_danger': ParagraphStyle('v_danger',
            fontName='Times-Bold', fontSize=9.5, leading=12,
            textColor=colors.HexColor('#DC2626'), alignment=1),
        'footer': ParagraphStyle('footer',
            fontName='Times-Roman', fontSize=8.5, leading=11, 
            textColor=colors.HexColor('#94A3B8')),
    }

def _base_table_style(header_color, alt_row_color):
    return TableStyle([
        ('BACKGROUND', (0,0), (-1,0), header_color),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [alt_row_color, colors.white]),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('TOPPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 6),
        ('RIGHTPADDING', (0,0), (-1,-1), 6),
        ('LINEBELOW', (0,0), (-1,0), 1.5, colors.HexColor('#0F172A')), # Navy blue line under the table headers
        ('LINEBELOW', (0,1), (-1,-1), 0.5, colors.HexColor('#FDE047')), 
    ])

def draw_page_border(canvas, doc):
    """Draws a crisp pink frame border around the document pages."""
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor('#F472B6')) 
    canvas.setLineWidth(1.2)
    inset = 0.35 * inch
    width, height = doc.pagesize
    canvas.rect(inset, inset, width - (2 * inset), height - (2 * inset))
    canvas.restoreState()

def generate_pdf(upi_rows, url_rows, export_type='both'):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=0.5*inch, rightMargin=0.5*inch,
                            topMargin=0.5*inch,  bottomMargin=0.5*inch)
    S = _styles()
    story = []

    titles = {
        'upi':   'UPI Fraud Detection — Scan Report',
        'links': 'Suspicious Link Scanner — Report',
        'both':  'UPI Guard — Full Security Report',
    }
    
    story.append(Paragraph(titles.get(export_type, titles['both']), S['title']))
    story.append(Paragraph(
        f"Generated: {datetime.datetime.now().strftime('%d %B %Y, %H:%M:%S')}  |  "
        f"UPI records: {len(upi_rows)}  |  Link scans: {len(url_rows)}",
        S['sub']))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0F172A'), spaceAfter=12))

    if export_type in ('upi', 'both'):
        _add_upi_section(story, upi_rows, S)

    if export_type in ('links', 'both'):
        _add_links_section(story, url_rows, S)

    story.append(Spacer(1, 0.2*inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#FDE047'), spaceAfter=6))
    story.append(Paragraph("Report generated by UPI Guard — Cybersecurity Project 2025", S['footer']))

    doc.build(story, onFirstPage=draw_page_border, onLaterPages=draw_page_border)
    buf.seek(0)
    return buf

def _get_verdict_style(verdict_str, style_dict):
    v = str(verdict_str).upper()
    if any(keyword in v for keyword in ["SAFE", "CLEAN"]):
        return style_dict['verdict_safe']
    if any(keyword in v for keyword in ["SUSPICIOUS", "FRAUD", "DANGEROUS", "MALICIOUS"]):
        return style_dict['verdict_danger']
    return style_dict['td_center']

def _add_upi_section(story, rows, S):
    story.append(Paragraph("UPI Fraud Detection Summary", S['h2']))

    if not rows:
        story.append(Paragraph("No UPI scan records found.", S['body']))
        story.append(Spacer(1, 0.15*inch))
        return

    safe  = sum(1 for r in rows if str(r[3]).upper() == "SAFE")
    susp  = sum(1 for r in rows if str(r[3]).upper() == "SUSPICIOUS")
    fraud = sum(1 for r in rows if str(r[3]).upper() == "FRAUD")

    summary_data = [
        [Paragraph("Safe", S['th_center']), Paragraph("Suspicious", S['th_center']), Paragraph("Fraud", S['th_center']), Paragraph("Total Scanned", S['th_center'])],
        [Paragraph(str(safe), S['td_center']), Paragraph(str(susp), S['td_center']), Paragraph(str(fraud), S['td_center']), Paragraph(str(len(rows)), S['td_center'])]
    ]
    summary = Table(summary_data, colWidths=[1.825*inch]*4)
    summary.setStyle(_base_table_style(colors.HexColor('#FDE047'), colors.HexColor('#FCE7F3')))
    story.append(summary)
    story.append(Spacer(1, 0.15*inch))

    story.append(Paragraph("Detailed UPI Scan Records", S['h2']))
    
    headers = ["#", "UPI ID", "Score", "Verdict", "Signals Detected", "Checked At"]
    data = [[Paragraph(h, S['th_center'] if i in [0, 2, 3] else S['th']) for i, h in enumerate(headers)]]
    
    for r in rows:
        v_style = _get_verdict_style(r[3], S)
        data.append([
            Paragraph(str(r[0]), S['td_center']),
            Paragraph(str(r[1]), S['td']),
            Paragraph(str(r[2]), S['td_center']),
            Paragraph(str(r[3]), v_style),
            Paragraph(str(r[4]) if r[4] else '', S['td']),
            Paragraph(str(r[5]) if r[5] else '', S['td'])
        ])
        
    tbl = Table(data, colWidths=[0.4*inch, 1.8*inch, 0.6*inch, 1.0*inch, 2.3*inch, 1.2*inch], repeatRows=1)
    tbl.setStyle(_base_table_style(colors.HexColor('#FDE047'), colors.HexColor('#FFFDF0')))
    story.append(tbl)
    story.append(Spacer(1, 0.2*inch))

def _add_links_section(story, rows, S):
    story.append(Paragraph("Suspicious Link Scanner Summary", S['h2']))
    story.append(Paragraph(
        "URLs scanned through threat intelligence platforms plus internal signal analysis "
        "for phishing indicators, structural mismatches, and fraud signatures.",
        S['body']
    ))

    if not rows:
        story.append(Paragraph("No URL scan records found.", S['body']))
        story.append(Spacer(1, 0.15*inch))
        return

    dangerous  = sum(1 for r in rows if r[2] and "DANGEROUS" in str(r[2]).upper())
    suspicious = sum(1 for r in rows if r[2] and "SUSPICIOUS" in str(r[2]).upper())
    clean      = sum(1 for r in rows if r[2] and "CLEAN" in str(r[2]).upper())

    summary_data = [
        [Paragraph("Dangerous", S['th_center']), Paragraph("Suspicious", S['th_center']), Paragraph("Clean", S['th_center']), Paragraph("Total Scanned", S['th_center'])],
        [Paragraph(str(dangerous), S['td_center']), Paragraph(str(suspicious), S['td_center']), Paragraph(str(clean), S['td_center']), Paragraph(str(len(rows)), S['td_center'])]
    ]
    summary = Table(summary_data, colWidths=[1.825*inch]*4)
    summary.setStyle(_base_table_style(colors.HexColor('#FDE047'), colors.HexColor('#FCE7F3')))
    story.append(summary)
    story.append(Spacer(1, 0.15*inch))

    story.append(Paragraph("Detailed URL Scan Records", S['h2']))
    
    headers = ["#", "URL Scanned", "Verdict", "Malicious", "Suspicious", "Engines", "Scanned At"]
    data = [[Paragraph(h, S['th_center'] if i in [0, 2, 3, 4, 5] else S['th']) for i, h in enumerate(headers)]]
    
    for r in rows:
        v_style = _get_verdict_style(r[2], S)
        data.append([
            Paragraph(str(r[0]), S['td_center']),
            Paragraph(str(r[1]), S['td']),
            Paragraph(str(r[2]) if r[2] else '', v_style),
            Paragraph(str(r[3]), S['td_center']),
            Paragraph(str(r[4]), S['td_center']),
            Paragraph(str(r[5]), S['td_center']),
            Paragraph(str(r[7]) if r[7] else '', S['td'])
        ])
        
    tbl = Table(data, colWidths=[0.35*inch, 2.1*inch, 1.1*inch, 0.65*inch, 0.75*inch, 0.55*inch, 1.8*inch], repeatRows=1)
    tbl.setStyle(_base_table_style(colors.HexColor('#FDE047'), colors.HexColor('#FFFDF0')))
    story.append(tbl)
    story.append(Spacer(1, 0.2*inch))